### ISSUE TITLE
FancyMenu is not compatible with Audio Extension

### ISSUE THREAD

**Issue by CSMMaster** [Keksuccino/FancyMenu-Audio-Extension#8]
Trying to start minecraft with Fancy Menu and Audio Extension installed, and received this error:

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'FancyMenu' (fancymenu) 3.0.3 with version 3.0.0 or later that is compatible with:
		 - fmextension_audio 1.1.2
More details:
	 - Mod 'FancyMenu' (fancymenu) 3.0.3 is incompatible with any version of mod 'FancyMenu Audio Extension' (fmextension_audio), but a matching version is present: 1.1.2!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

I currently have FancyMenu v3.0.4 and Audio Extension 1.1.2 installed including all necessary API / LIB.

**Comment by Keksuccino** [comment]
Yes, it is incompatible because it's an extension for FancyMenu v2. You are using v3.
You don't need the extension for v3, because its features are in the base mod now.
